apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: app
  namespace: <YOUR_PROJECT_NAME_HERE>
spec:
  encryptedData:
    #  Go to https://socialgouv.github.io/sre-tools/ to seal your secrets
    MY_SECRET_VARIABLE_1: <YOUR_SEALED_SECRET_HERE>
    MY_SECRET_VARIABLE_2: <YOUR_SEALED_SECRET_HERE>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: app
    type: Opaque
